web:
  build: ./docker-compose/apache-php/
  links:
   - db
   - mailcatcher
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./src:/var/www/symfony
   - ./docker-compose/data/log/apache2:/var/log/apache2
db:
  image: mariadb
  ports:
   - "3306:3306"
  volumes_from:
   - symfony-data
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: symfony
    MYSQL_USER: symfony
    MYSQL_PASSWORD: symfony
mailcatcher:
  image: alexisno/mailcatcher
  ports:
   - "1080:1080"
