web:
  build: ./docker-compose/nginx-php/
  links:
   - db
   - memcached
   - mailcatcher
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./src:/var/www/magento
   - ./docker-compose/data/log/nginx:/var/log/nginx
db:
  image: mariadb
  ports:
   - "3306:3306"
  volumes_from:
   - magento-data
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: magento
    MYSQL_USER: magento
    MYSQL_PASSWORD: magento
memcached:
  image: memcached
mailcatcher:
  image: alexisno/mailcatcher
  ports:
   - "1080:1080"
