web:
  build: ./docker-compose/nginx-php/
  links:
   - db
   - mailcatcher
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./src:/var/www/symfony
   - ./docker-compose/data/log/nginx:/var/log/nginx
db:
  image: postgres
  ports:
   - "5432:5432"
  volumes_from:
   - symfony-data
  environment:
    POSTGRES_PASSWORD: "symfony"
    POSTGRES_USER: "symfony"
mailcatcher:
  image: alexisno/mailcatcher-dev
  ports:
   - "1080:1080"
